version: '3'
volumes: 
  dados:
networks:
  rede_banco:
  rede_app:
  rede_fila:
services:
  db:
    container_name: db_maddytec
    image: postgres
    environment:
      # Acesso ao banco sem autenticação
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dados:/var/lib/postgresql/data
      # Scripts executados na inicialização do container
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - rede_banco
  app:
    container_name: app_maddytec
    image: nginx:1.13
    # Site
    volumes: 
      - ./web:/usr/share/nginx/html/
      #Configuração do proxy reverso
      - ./app/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - rede_app
    depends_on: 
      - api
  api:
    container_name: api_maddytec
    image: python:3.6
    volumes: 
      - ./api:/api
    working_dir: /api
    command: bash ./api.sh
    networks: 
      - rede_banco
      - rede_app
      - rede_fila
    depends_on: 
      - db
      - queue
  queue:
    image: redis:3.2
    networks: 
      - rede_fila
  worker:
    image: python:3.6
    volumes: 
      - ./worker:/worker
    working_dir: /worker
    command: bash ./api.sh
    networks: 
      - rede_fila
    depends_on: 
      - queue