version: '3'
volumes: 
  dados:
services:
  db:
    container_name: db_maddytec
    image: postgres
    environment:
      # Acesso ao banco sem autenticação
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - dados:/var/lib/postgresql/data
      # Scripts executados na inicialização do container
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    container_name: app_maddytec
    image: nginx:1.13
    # Site
    volumes: 
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80
  api:
    container_name: api_maddytec
    image: python:3.6
    volumes: 
      - ./api:/api
    working_dir: /api
    command: bash ./api.sh
    ports:
      - 8080:8080